name: ETL
'on':
  push:
    branches: main
  schedule:
   - cron: "0 7 * * *"
jobs:
  id_0:
    name: <bound method ETL.start of batch_framework-parallize-MapReduce-in-name_trigger_new-out-latest_new>
    needs: []
    secrets: inherit
    uses: ./.github/workflows/job.yml
    with:
      task-id: id_0
      task-name: <bound method ETL.start of batch_framework-parallize-MapReduce-in-name_trigger_new-out-latest_new>