jobs:
  id_0:
    name: <bound method ETL.start of batch_framework-parallize-MapReduce-in-name_trigger_new-out-latest_new>
    needs: []
    secrets: inherit
    uses: ./.github/workflows/job.yml
    with:
      task-id: id_0
      task-name: <bound method ETL.start of batch_framework-parallize-MapReduce-in-name_trigger_new-out-latest_new>
  id_1:
    name: <bound method ETL.start of src-main-SimplePyPiCanonicalize-out-latest_package-latest_requirement-latest_url>
    needs: []
    secrets: inherit
    uses: ./.github/workflows/job.yml
    with:
      task-id: id_1
      task-name: <bound method ETL.start of src-main-SimplePyPiCanonicalize-out-latest_package-latest_requirement-latest_url>
  id_10:
    name: name_trigger_new
    needs:
    - id_19
    - id_0
    runs-on: ubuntu-latest
    steps:
    - name: name_trigger_new
      run: echo name_trigger_new
  id_11:
    name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new.AddPartitionKey
    needs:
    - id_10
    secrets: inherit
    uses: ./.github/workflows/job.yml
    with:
      task-id: id_11
      task-name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new.AddPartitionKey
  id_12:
    name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new.Divide
    needs:
    - id_17
    secrets: inherit
    uses: ./.github/workflows/job.yml
    with:
      task-id: id_12
      task-name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new.Divide
  id_13:
    name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new.MapClass.0
    needs:
    - id_16
    secrets: inherit
    uses: ./.github/workflows/job.yml
    with:
      task-id: id_13
      task-name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new.MapClass.0
  id_14:
    name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new.Merge
    needs:
    - id_15
    secrets: inherit
    uses: ./.github/workflows/job.yml
    with:
      task-id: id_14
      task-name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new.Merge
  id_15:
    name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_latest_new_0
    needs:
    - id_13
    runs-on: ubuntu-latest
    steps:
    - name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_latest_new_0
      run: echo src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_latest_new_0
  id_16:
    name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_name_trigger_new_0
    needs:
    - id_12
    runs-on: ubuntu-latest
    steps:
    - name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_name_trigger_new_0
      run: echo src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_name_trigger_new_0
  id_17:
    name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_name_trigger_new_full
    needs:
    - id_11
    runs-on: ubuntu-latest
    steps:
    - name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_name_trigger_new_full
      run: echo src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_name_trigger_new_full
  id_18:
    name: src-crawl-LatestUpdator-in-latest_new-out-latest
    needs:
    - id_5
    secrets: inherit
    uses: ./.github/workflows/job.yml
    with:
      task-id: id_18
      task-name: src-crawl-LatestUpdator-in-latest_new-out-latest
  id_19:
    name: src-main-NewPackageExtractor-in-name_trigger-out-name_trigger_new
    needs:
    - id_9
    secrets: inherit
    uses: ./.github/workflows/job.yml
    with:
      task-id: id_19
      task-name: src-main-NewPackageExtractor-in-name_trigger-out-name_trigger_new
  id_2:
    name: <bound method ETLGroup._end of batch_framework-parallize-MapReduce-in-name_trigger_new-out-latest_new>
    needs:
    - id_5
    secrets: inherit
    uses: ./.github/workflows/job.yml
    with:
      task-id: id_2
      task-name: <bound method ETLGroup._end of batch_framework-parallize-MapReduce-in-name_trigger_new-out-latest_new>
  id_20:
    name: src-tabularize-LatestTabularize-in-latest-out-latest_package-latest_requirement-latest_url
    needs:
    - id_4
    secrets: inherit
    uses: ./.github/workflows/job.yml
    with:
      task-id: id_20
      task-name: src-tabularize-LatestTabularize-in-latest-out-latest_package-latest_requirement-latest_url
  id_21:
    name: src-trigger-PyPiNameTrigger-out-name_trigger
    needs: []
    secrets: inherit
    uses: ./.github/workflows/job.yml
    with:
      task-id: id_21
      task-name: src-trigger-PyPiNameTrigger-out-name_trigger
  id_3:
    name: <bound method ETLGroup._end of src-main-SimplePyPiCanonicalize-out-latest_package-latest_requirement-latest_url>
    needs:
    - id_7
    - id_8
    - id_6
    secrets: inherit
    uses: ./.github/workflows/job.yml
    with:
      task-id: id_3
      task-name: <bound method ETLGroup._end of src-main-SimplePyPiCanonicalize-out-latest_package-latest_requirement-latest_url>
  id_4:
    name: latest
    needs:
    - id_18
    runs-on: ubuntu-latest
    steps:
    - name: latest
      run: echo latest
  id_5:
    name: latest_new
    needs:
    - id_14
    runs-on: ubuntu-latest
    steps:
    - name: latest_new
      run: echo latest_new
  id_6:
    name: latest_package
    needs:
    - id_20
    runs-on: ubuntu-latest
    steps:
    - name: latest_package
      run: echo latest_package
  id_7:
    name: latest_requirement
    needs:
    - id_20
    runs-on: ubuntu-latest
    steps:
    - name: latest_requirement
      run: echo latest_requirement
  id_8:
    name: latest_url
    needs:
    - id_20
    runs-on: ubuntu-latest
    steps:
    - name: latest_url
      run: echo latest_url
  id_9:
    name: name_trigger
    needs:
    - id_21
    runs-on: ubuntu-latest
    steps:
    - name: name_trigger
      run: echo name_trigger
name: ETL
'on':
  push:
    branches: main
