jobs:
  id_0:
    name: <bound method ETL.start of batch_framework-parallize-MapReduce-in-name_trigger_new-out-latest_new>
    needs: []
    secrets: inherit
    uses: ./.github/workflows/job.yml
    with:
      task-id: id_0
      task-name: <bound method ETL.start of batch_framework-parallize-MapReduce-in-name_trigger_new-out-latest_new>
  id_1:
    name: <bound method ETL.start of src-main-SimplePyPiCanonicalize-out-latest_package-latest_requirement-latest_url>
    needs: []
    secrets: inherit
    uses: ./.github/workflows/job.yml
    with:
      task-id: id_1
      task-name: <bound method ETL.start of src-main-SimplePyPiCanonicalize-out-latest_package-latest_requirement-latest_url>
  id_10:
    name: name_trigger_new
    needs:
    - id_40
    - id_0
    runs-on: ubuntu-latest
    steps:
    - name: name_trigger_new
      run: echo name_trigger_new
  id_11:
    name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new.AddPartitionKey
    needs:
    - id_10
    secrets: inherit
    uses: ./.github/workflows/job.yml
    with:
      task-id: id_11
      task-name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new.AddPartitionKey
  id_12:
    name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new.Divide
    needs:
    - id_38
    secrets: inherit
    uses: ./.github/workflows/job.yml
    with:
      task-id: id_12
      task-name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new.Divide
  id_13:
    name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new.MapClass.0
    needs:
    - id_30
    secrets: inherit
    uses: ./.github/workflows/job.yml
    with:
      task-id: id_13
      task-name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new.MapClass.0
  id_14:
    name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new.MapClass.1
    needs:
    - id_31
    secrets: inherit
    uses: ./.github/workflows/job.yml
    with:
      task-id: id_14
      task-name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new.MapClass.1
  id_15:
    name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new.MapClass.2
    needs:
    - id_32
    secrets: inherit
    uses: ./.github/workflows/job.yml
    with:
      task-id: id_15
      task-name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new.MapClass.2
  id_16:
    name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new.MapClass.3
    needs:
    - id_33
    secrets: inherit
    uses: ./.github/workflows/job.yml
    with:
      task-id: id_16
      task-name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new.MapClass.3
  id_17:
    name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new.MapClass.4
    needs:
    - id_34
    secrets: inherit
    uses: ./.github/workflows/job.yml
    with:
      task-id: id_17
      task-name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new.MapClass.4
  id_18:
    name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new.MapClass.5
    needs:
    - id_35
    secrets: inherit
    uses: ./.github/workflows/job.yml
    with:
      task-id: id_18
      task-name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new.MapClass.5
  id_19:
    name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new.MapClass.6
    needs:
    - id_36
    secrets: inherit
    uses: ./.github/workflows/job.yml
    with:
      task-id: id_19
      task-name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new.MapClass.6
  id_2:
    name: <bound method ETLGroup._end of batch_framework-parallize-MapReduce-in-name_trigger_new-out-latest_new>
    needs:
    - id_5
    secrets: inherit
    uses: ./.github/workflows/job.yml
    with:
      task-id: id_2
      task-name: <bound method ETLGroup._end of batch_framework-parallize-MapReduce-in-name_trigger_new-out-latest_new>
  id_20:
    name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new.MapClass.7
    needs:
    - id_37
    secrets: inherit
    uses: ./.github/workflows/job.yml
    with:
      task-id: id_20
      task-name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new.MapClass.7
  id_21:
    name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new.Merge
    needs:
    - id_28
    - id_22
    - id_29
    - id_26
    - id_27
    - id_25
    - id_23
    - id_24
    secrets: inherit
    uses: ./.github/workflows/job.yml
    with:
      task-id: id_21
      task-name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new.Merge
  id_22:
    name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_latest_new_0
    needs:
    - id_13
    runs-on: ubuntu-latest
    steps:
    - name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_latest_new_0
      run: echo src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_latest_new_0
  id_23:
    name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_latest_new_1
    needs:
    - id_14
    runs-on: ubuntu-latest
    steps:
    - name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_latest_new_1
      run: echo src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_latest_new_1
  id_24:
    name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_latest_new_2
    needs:
    - id_15
    runs-on: ubuntu-latest
    steps:
    - name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_latest_new_2
      run: echo src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_latest_new_2
  id_25:
    name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_latest_new_3
    needs:
    - id_16
    runs-on: ubuntu-latest
    steps:
    - name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_latest_new_3
      run: echo src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_latest_new_3
  id_26:
    name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_latest_new_4
    needs:
    - id_17
    runs-on: ubuntu-latest
    steps:
    - name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_latest_new_4
      run: echo src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_latest_new_4
  id_27:
    name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_latest_new_5
    needs:
    - id_18
    runs-on: ubuntu-latest
    steps:
    - name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_latest_new_5
      run: echo src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_latest_new_5
  id_28:
    name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_latest_new_6
    needs:
    - id_19
    runs-on: ubuntu-latest
    steps:
    - name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_latest_new_6
      run: echo src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_latest_new_6
  id_29:
    name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_latest_new_7
    needs:
    - id_20
    runs-on: ubuntu-latest
    steps:
    - name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_latest_new_7
      run: echo src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_latest_new_7
  id_3:
    name: <bound method ETLGroup._end of src-main-SimplePyPiCanonicalize-out-latest_package-latest_requirement-latest_url>
    needs:
    - id_6
    - id_8
    - id_7
    secrets: inherit
    uses: ./.github/workflows/job.yml
    with:
      task-id: id_3
      task-name: <bound method ETLGroup._end of src-main-SimplePyPiCanonicalize-out-latest_package-latest_requirement-latest_url>
  id_30:
    name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_name_trigger_new_0
    needs:
    - id_12
    runs-on: ubuntu-latest
    steps:
    - name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_name_trigger_new_0
      run: echo src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_name_trigger_new_0
  id_31:
    name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_name_trigger_new_1
    needs:
    - id_12
    runs-on: ubuntu-latest
    steps:
    - name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_name_trigger_new_1
      run: echo src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_name_trigger_new_1
  id_32:
    name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_name_trigger_new_2
    needs:
    - id_12
    runs-on: ubuntu-latest
    steps:
    - name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_name_trigger_new_2
      run: echo src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_name_trigger_new_2
  id_33:
    name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_name_trigger_new_3
    needs:
    - id_12
    runs-on: ubuntu-latest
    steps:
    - name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_name_trigger_new_3
      run: echo src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_name_trigger_new_3
  id_34:
    name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_name_trigger_new_4
    needs:
    - id_12
    runs-on: ubuntu-latest
    steps:
    - name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_name_trigger_new_4
      run: echo src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_name_trigger_new_4
  id_35:
    name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_name_trigger_new_5
    needs:
    - id_12
    runs-on: ubuntu-latest
    steps:
    - name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_name_trigger_new_5
      run: echo src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_name_trigger_new_5
  id_36:
    name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_name_trigger_new_6
    needs:
    - id_12
    runs-on: ubuntu-latest
    steps:
    - name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_name_trigger_new_6
      run: echo src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_name_trigger_new_6
  id_37:
    name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_name_trigger_new_7
    needs:
    - id_12
    runs-on: ubuntu-latest
    steps:
    - name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_name_trigger_new_7
      run: echo src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_name_trigger_new_7
  id_38:
    name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_name_trigger_new_full
    needs:
    - id_11
    runs-on: ubuntu-latest
    steps:
    - name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_name_trigger_new_full
      run: echo src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_name_trigger_new_full
  id_39:
    name: src-crawl-LatestUpdator-in-latest_new-out-latest
    needs:
    - id_5
    secrets: inherit
    uses: ./.github/workflows/job.yml
    with:
      task-id: id_39
      task-name: src-crawl-LatestUpdator-in-latest_new-out-latest
  id_4:
    name: latest
    needs:
    - id_39
    runs-on: ubuntu-latest
    steps:
    - name: latest
      run: echo latest
  id_40:
    name: src-main-NewPackageExtractor-in-name_trigger-out-name_trigger_new
    needs:
    - id_9
    secrets: inherit
    uses: ./.github/workflows/job.yml
    with:
      task-id: id_40
      task-name: src-main-NewPackageExtractor-in-name_trigger-out-name_trigger_new
  id_41:
    name: src-tabularize-LatestTabularize-in-latest-out-latest_package-latest_requirement-latest_url
    needs:
    - id_4
    secrets: inherit
    uses: ./.github/workflows/job.yml
    with:
      task-id: id_41
      task-name: src-tabularize-LatestTabularize-in-latest-out-latest_package-latest_requirement-latest_url
  id_42:
    name: src-trigger-PyPiNameTrigger-out-name_trigger
    needs: []
    secrets: inherit
    uses: ./.github/workflows/job.yml
    with:
      task-id: id_42
      task-name: src-trigger-PyPiNameTrigger-out-name_trigger
  id_5:
    name: latest_new
    needs:
    - id_21
    runs-on: ubuntu-latest
    steps:
    - name: latest_new
      run: echo latest_new
  id_6:
    name: latest_package
    needs:
    - id_41
    runs-on: ubuntu-latest
    steps:
    - name: latest_package
      run: echo latest_package
  id_7:
    name: latest_requirement
    needs:
    - id_41
    runs-on: ubuntu-latest
    steps:
    - name: latest_requirement
      run: echo latest_requirement
  id_8:
    name: latest_url
    needs:
    - id_41
    runs-on: ubuntu-latest
    steps:
    - name: latest_url
      run: echo latest_url
  id_9:
    name: name_trigger
    needs:
    - id_42
    runs-on: ubuntu-latest
    steps:
    - name: name_trigger
      run: echo name_trigger
name: ETL
'on':
  push:
    branches: main
