jobs:
  id_0:
    name: <bound method ETL.start of batch_framework-parallize-MapReduce-in-name_trigger_new-out-latest_new>
    needs: []
    runs-on: ubuntu-latest
    steps:
    - name: start
      run: echo '<bound method ETL.start of batch_framework-parallize-MapReduce-in-name_trigger_new-out-latest_new>'
  id_1:
    name: <bound method ETL.start of src-main-SimplePyPiCanonicalize-out-latest>
    needs: []
    runs-on: ubuntu-latest
    steps:
    - name: start
      run: echo '<bound method ETL.start of src-main-SimplePyPiCanonicalize-out-latest>'
  id_10:
    name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new.MapClass.0
    needs:
    - id_13
    secrets: inherit
    uses: ./.github/workflows/job.yml
    with:
      task-id: id_10
      task-name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new.MapClass.0
  id_11:
    name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new.Merge
    needs:
    - id_12
    secrets: inherit
    uses: ./.github/workflows/job.yml
    with:
      task-id: id_11
      task-name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new.Merge
  id_12:
    name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_latest_new_0
    needs:
    - id_10
    runs-on: ubuntu-latest
    steps:
    - name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_latest_new_0
      run: echo 'src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_latest_new_0'
  id_13:
    name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_name_trigger_new_0
    needs:
    - id_9
    runs-on: ubuntu-latest
    steps:
    - name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_name_trigger_new_0
      run: echo 'src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_name_trigger_new_0'
  id_14:
    name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_name_trigger_new_full
    needs:
    - id_8
    runs-on: ubuntu-latest
    steps:
    - name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_name_trigger_new_full
      run: echo 'src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new_name_trigger_new_full'
  id_15:
    name: src-crawl-LatestUpdator-in-latest_new-out-latest
    needs:
    - id_5
    secrets: inherit
    uses: ./.github/workflows/job.yml
    with:
      task-id: id_15
      task-name: src-crawl-LatestUpdator-in-latest_new-out-latest
  id_16:
    name: src-main-NewPackageExtractor-in-name_trigger-out-name_trigger_new
    needs:
    - id_6
    secrets: inherit
    uses: ./.github/workflows/job.yml
    with:
      task-id: id_16
      task-name: src-main-NewPackageExtractor-in-name_trigger-out-name_trigger_new
  id_17:
    name: src-trigger-PyPiNameTrigger-out-name_trigger
    needs: []
    secrets: inherit
    uses: ./.github/workflows/job.yml
    with:
      task-id: id_17
      task-name: src-trigger-PyPiNameTrigger-out-name_trigger
  id_2:
    name: <bound method ETLGroup._end of batch_framework-parallize-MapReduce-in-name_trigger_new-out-latest_new>
    needs:
    - id_5
    secrets: inherit
    uses: ./.github/workflows/job.yml
    with:
      task-id: id_2
      task-name: <bound method ETLGroup._end of batch_framework-parallize-MapReduce-in-name_trigger_new-out-latest_new>
  id_3:
    name: <bound method ETLGroup._end of src-main-SimplePyPiCanonicalize-out-latest>
    needs:
    - id_4
    secrets: inherit
    uses: ./.github/workflows/job.yml
    with:
      task-id: id_3
      task-name: <bound method ETLGroup._end of src-main-SimplePyPiCanonicalize-out-latest>
  id_4:
    name: latest
    needs:
    - id_15
    runs-on: ubuntu-latest
    steps:
    - name: latest
      run: echo 'latest'
  id_5:
    name: latest_new
    needs:
    - id_11
    runs-on: ubuntu-latest
    steps:
    - name: latest_new
      run: echo 'latest_new'
  id_6:
    name: name_trigger
    needs:
    - id_17
    runs-on: ubuntu-latest
    steps:
    - name: name_trigger
      run: echo 'name_trigger'
  id_7:
    name: name_trigger_new
    needs:
    - id_0
    - id_16
    runs-on: ubuntu-latest
    steps:
    - name: name_trigger_new
      run: echo 'name_trigger_new'
  id_8:
    name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new.AddPartitionKey
    needs:
    - id_7
    secrets: inherit
    uses: ./.github/workflows/job.yml
    with:
      task-id: id_8
      task-name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new.AddPartitionKey
  id_9:
    name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new.Divide
    needs:
    - id_14
    secrets: inherit
    uses: ./.github/workflows/job.yml
    with:
      task-id: id_9
      task-name: src-crawl-LatestDownloader-in-name_trigger_new-out-latest_new.Divide
name: ETL
'on':
  push:
    branches: main
